---
- hosts: webserver
  become: yes
  tasks:
    - name: uninstall apache first
      apt: apache2
      state:absent
    - name: install apache on webserver
      apt:
        name: apache2
        state: present
    - name: Restart apache
      service:
        name: apache2
        state: restarted
     
   
